// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gsx.proto

package gsxproto

import (
	fmt "fmt"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	proto "github.com/yyyiue/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

var E_GoprotoEnumPrefix = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62001,
	Name:          "gsx.goproto_enum_prefix",
	Tag:           "varint,62001,opt,name=goproto_enum_prefix",
	Filename:      "gsx.proto",
}

var E_GoprotoEnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62021,
	Name:          "gsx.goproto_enum_stringer",
	Tag:           "varint,62021,opt,name=goproto_enum_stringer",
	Filename:      "gsx.proto",
}

var E_EnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62022,
	Name:          "gsx.enum_stringer",
	Tag:           "varint,62022,opt,name=enum_stringer",
	Filename:      "gsx.proto",
}

var E_EnumCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         62023,
	Name:          "gsx.enum_customname",
	Tag:           "bytes,62023,opt,name=enum_customname",
	Filename:      "gsx.proto",
}

var E_Enumdecl = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62024,
	Name:          "gsx.enumdecl",
	Tag:           "varint,62024,opt,name=enumdecl",
	Filename:      "gsx.proto",
}

var E_EnumvalueCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         66001,
	Name:          "gsx.enumvalue_customname",
	Tag:           "bytes,66001,opt,name=enumvalue_customname",
	Filename:      "gsx.proto",
}

var E_GoprotoGettersAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63001,
	Name:          "gsx.goproto_getters_all",
	Tag:           "varint,63001,opt,name=goproto_getters_all",
	Filename:      "gsx.proto",
}

var E_GoprotoEnumPrefixAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63002,
	Name:          "gsx.goproto_enum_prefix_all",
	Tag:           "varint,63002,opt,name=goproto_enum_prefix_all",
	Filename:      "gsx.proto",
}

var E_GoprotoStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63003,
	Name:          "gsx.goproto_stringer_all",
	Tag:           "varint,63003,opt,name=goproto_stringer_all",
	Filename:      "gsx.proto",
}

var E_VerboseEqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63004,
	Name:          "gsx.verbose_equal_all",
	Tag:           "varint,63004,opt,name=verbose_equal_all",
	Filename:      "gsx.proto",
}

var E_FaceAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63005,
	Name:          "gsx.face_all",
	Tag:           "varint,63005,opt,name=face_all",
	Filename:      "gsx.proto",
}

var E_GostringAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63006,
	Name:          "gsx.gostring_all",
	Tag:           "varint,63006,opt,name=gostring_all",
	Filename:      "gsx.proto",
}

var E_PopulateAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63007,
	Name:          "gsx.populate_all",
	Tag:           "varint,63007,opt,name=populate_all",
	Filename:      "gsx.proto",
}

var E_StringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63008,
	Name:          "gsx.stringer_all",
	Tag:           "varint,63008,opt,name=stringer_all",
	Filename:      "gsx.proto",
}

var E_OnlyoneAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63009,
	Name:          "gsx.onlyone_all",
	Tag:           "varint,63009,opt,name=onlyone_all",
	Filename:      "gsx.proto",
}

var E_EqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63013,
	Name:          "gsx.equal_all",
	Tag:           "varint,63013,opt,name=equal_all",
	Filename:      "gsx.proto",
}

var E_DescriptionAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63014,
	Name:          "gsx.description_all",
	Tag:           "varint,63014,opt,name=description_all",
	Filename:      "gsx.proto",
}

var E_TestgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63015,
	Name:          "gsx.testgen_all",
	Tag:           "varint,63015,opt,name=testgen_all",
	Filename:      "gsx.proto",
}

var E_BenchgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63016,
	Name:          "gsx.benchgen_all",
	Tag:           "varint,63016,opt,name=benchgen_all",
	Filename:      "gsx.proto",
}

var E_MarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63017,
	Name:          "gsx.marshaler_all",
	Tag:           "varint,63017,opt,name=marshaler_all",
	Filename:      "gsx.proto",
}

var E_UnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63018,
	Name:          "gsx.unmarshaler_all",
	Tag:           "varint,63018,opt,name=unmarshaler_all",
	Filename:      "gsx.proto",
}

var E_StableMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63019,
	Name:          "gsx.stable_marshaler_all",
	Tag:           "varint,63019,opt,name=stable_marshaler_all",
	Filename:      "gsx.proto",
}

var E_SizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63020,
	Name:          "gsx.sizer_all",
	Tag:           "varint,63020,opt,name=sizer_all",
	Filename:      "gsx.proto",
}

var E_GoprotoEnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63021,
	Name:          "gsx.goproto_enum_stringer_all",
	Tag:           "varint,63021,opt,name=goproto_enum_stringer_all",
	Filename:      "gsx.proto",
}

var E_EnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63022,
	Name:          "gsx.enum_stringer_all",
	Tag:           "varint,63022,opt,name=enum_stringer_all",
	Filename:      "gsx.proto",
}

var E_UnsafeMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63023,
	Name:          "gsx.unsafe_marshaler_all",
	Tag:           "varint,63023,opt,name=unsafe_marshaler_all",
	Filename:      "gsx.proto",
}

var E_UnsafeUnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63024,
	Name:          "gsx.unsafe_unmarshaler_all",
	Tag:           "varint,63024,opt,name=unsafe_unmarshaler_all",
	Filename:      "gsx.proto",
}

var E_GoprotoExtensionsMapAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63025,
	Name:          "gsx.goproto_extensions_map_all",
	Tag:           "varint,63025,opt,name=goproto_extensions_map_all",
	Filename:      "gsx.proto",
}

var E_GoprotoUnrecognizedAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63026,
	Name:          "gsx.goproto_unrecognized_all",
	Tag:           "varint,63026,opt,name=goproto_unrecognized_all",
	Filename:      "gsx.proto",
}

var E_GogoprotoImport = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63027,
	Name:          "gsx.gogoproto_import",
	Tag:           "varint,63027,opt,name=gogoproto_import",
	Filename:      "gsx.proto",
}

var E_ProtosizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63028,
	Name:          "gsx.protosizer_all",
	Tag:           "varint,63028,opt,name=protosizer_all",
	Filename:      "gsx.proto",
}

var E_CompareAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63029,
	Name:          "gsx.compare_all",
	Tag:           "varint,63029,opt,name=compare_all",
	Filename:      "gsx.proto",
}

var E_TypedeclAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63030,
	Name:          "gsx.typedecl_all",
	Tag:           "varint,63030,opt,name=typedecl_all",
	Filename:      "gsx.proto",
}

var E_EnumdeclAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63031,
	Name:          "gsx.enumdecl_all",
	Tag:           "varint,63031,opt,name=enumdecl_all",
	Filename:      "gsx.proto",
}

var E_GoprotoRegistration = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63032,
	Name:          "gsx.goproto_registration",
	Tag:           "varint,63032,opt,name=goproto_registration",
	Filename:      "gsx.proto",
}

var E_MessagenameAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63033,
	Name:          "gsx.messagename_all",
	Tag:           "varint,63033,opt,name=messagename_all",
	Filename:      "gsx.proto",
}

var E_GoprotoSizecacheAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63034,
	Name:          "gsx.goproto_sizecache_all",
	Tag:           "varint,63034,opt,name=goproto_sizecache_all",
	Filename:      "gsx.proto",
}

var E_GoprotoUnkeyedAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63035,
	Name:          "gsx.goproto_unkeyed_all",
	Tag:           "varint,63035,opt,name=goproto_unkeyed_all",
	Filename:      "gsx.proto",
}

var E_GoprotoGetters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64001,
	Name:          "gsx.goproto_getters",
	Tag:           "varint,64001,opt,name=goproto_getters",
	Filename:      "gsx.proto",
}

var E_GoprotoStringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64003,
	Name:          "gsx.goproto_stringer",
	Tag:           "varint,64003,opt,name=goproto_stringer",
	Filename:      "gsx.proto",
}

var E_VerboseEqual = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64004,
	Name:          "gsx.verbose_equal",
	Tag:           "varint,64004,opt,name=verbose_equal",
	Filename:      "gsx.proto",
}

var E_Face = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64005,
	Name:          "gsx.face",
	Tag:           "varint,64005,opt,name=face",
	Filename:      "gsx.proto",
}

var E_Gostring = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64006,
	Name:          "gsx.gostring",
	Tag:           "varint,64006,opt,name=gostring",
	Filename:      "gsx.proto",
}

var E_Populate = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64007,
	Name:          "gsx.populate",
	Tag:           "varint,64007,opt,name=populate",
	Filename:      "gsx.proto",
}

var E_Stringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         67008,
	Name:          "gsx.stringer",
	Tag:           "varint,67008,opt,name=stringer",
	Filename:      "gsx.proto",
}

var E_Onlyone = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64009,
	Name:          "gsx.onlyone",
	Tag:           "varint,64009,opt,name=onlyone",
	Filename:      "gsx.proto",
}

var E_Equal = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64013,
	Name:          "gsx.equal",
	Tag:           "varint,64013,opt,name=equal",
	Filename:      "gsx.proto",
}

var E_Description = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64014,
	Name:          "gsx.description",
	Tag:           "varint,64014,opt,name=description",
	Filename:      "gsx.proto",
}

var E_Testgen = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64015,
	Name:          "gsx.testgen",
	Tag:           "varint,64015,opt,name=testgen",
	Filename:      "gsx.proto",
}

var E_Benchgen = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64016,
	Name:          "gsx.benchgen",
	Tag:           "varint,64016,opt,name=benchgen",
	Filename:      "gsx.proto",
}

var E_Marshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64017,
	Name:          "gsx.marshaler",
	Tag:           "varint,64017,opt,name=marshaler",
	Filename:      "gsx.proto",
}

var E_Unmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64018,
	Name:          "gsx.unmarshaler",
	Tag:           "varint,64018,opt,name=unmarshaler",
	Filename:      "gsx.proto",
}

var E_StableMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64019,
	Name:          "gsx.stable_marshaler",
	Tag:           "varint,64019,opt,name=stable_marshaler",
	Filename:      "gsx.proto",
}

var E_Sizer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64020,
	Name:          "gsx.sizer",
	Tag:           "varint,64020,opt,name=sizer",
	Filename:      "gsx.proto",
}

var E_UnsafeMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64023,
	Name:          "gsx.unsafe_marshaler",
	Tag:           "varint,64023,opt,name=unsafe_marshaler",
	Filename:      "gsx.proto",
}

var E_UnsafeUnmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64024,
	Name:          "gsx.unsafe_unmarshaler",
	Tag:           "varint,64024,opt,name=unsafe_unmarshaler",
	Filename:      "gsx.proto",
}

var E_GoprotoExtensionsMap = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64025,
	Name:          "gsx.goproto_extensions_map",
	Tag:           "varint,64025,opt,name=goproto_extensions_map",
	Filename:      "gsx.proto",
}

var E_GoprotoUnrecognized = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64026,
	Name:          "gsx.goproto_unrecognized",
	Tag:           "varint,64026,opt,name=goproto_unrecognized",
	Filename:      "gsx.proto",
}

var E_Protosizer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64028,
	Name:          "gsx.protosizer",
	Tag:           "varint,64028,opt,name=protosizer",
	Filename:      "gsx.proto",
}

var E_Compare = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64029,
	Name:          "gsx.compare",
	Tag:           "varint,64029,opt,name=compare",
	Filename:      "gsx.proto",
}

var E_Typedecl = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64030,
	Name:          "gsx.typedecl",
	Tag:           "varint,64030,opt,name=typedecl",
	Filename:      "gsx.proto",
}

var E_Messagename = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64033,
	Name:          "gsx.messagename",
	Tag:           "varint,64033,opt,name=messagename",
	Filename:      "gsx.proto",
}

var E_GoprotoSizecache = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64034,
	Name:          "gsx.goproto_sizecache",
	Tag:           "varint,64034,opt,name=goproto_sizecache",
	Filename:      "gsx.proto",
}

var E_GoprotoUnkeyed = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64035,
	Name:          "gsx.goproto_unkeyed",
	Tag:           "varint,64035,opt,name=goproto_unkeyed",
	Filename:      "gsx.proto",
}

var E_Nullable = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65001,
	Name:          "gsx.nullable",
	Tag:           "varint,65001,opt,name=nullable",
	Filename:      "gsx.proto",
}

var E_Embed = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65002,
	Name:          "gsx.embed",
	Tag:           "varint,65002,opt,name=embed",
	Filename:      "gsx.proto",
}

var E_Customtype = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65003,
	Name:          "gsx.customtype",
	Tag:           "bytes,65003,opt,name=customtype",
	Filename:      "gsx.proto",
}

var E_Customname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65004,
	Name:          "gsx.customname",
	Tag:           "bytes,65004,opt,name=customname",
	Filename:      "gsx.proto",
}

var E_Jsontag = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65005,
	Name:          "gsx.jsontag",
	Tag:           "bytes,65005,opt,name=jsontag",
	Filename:      "gsx.proto",
}

var E_Moretags = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65006,
	Name:          "gsx.moretags",
	Tag:           "bytes,65006,opt,name=moretags",
	Filename:      "gsx.proto",
}

var E_Casttype = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65007,
	Name:          "gsx.casttype",
	Tag:           "bytes,65007,opt,name=casttype",
	Filename:      "gsx.proto",
}

var E_Castkey = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65008,
	Name:          "gsx.castkey",
	Tag:           "bytes,65008,opt,name=castkey",
	Filename:      "gsx.proto",
}

var E_Castvalue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65009,
	Name:          "gsx.castvalue",
	Tag:           "bytes,65009,opt,name=castvalue",
	Filename:      "gsx.proto",
}

var E_Stdtime = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65010,
	Name:          "gsx.stdtime",
	Tag:           "varint,65010,opt,name=stdtime",
	Filename:      "gsx.proto",
}

var E_Stdduration = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65011,
	Name:          "gsx.stdduration",
	Tag:           "varint,65011,opt,name=stdduration",
	Filename:      "gsx.proto",
}

var E_Wktpointer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65012,
	Name:          "gsx.wktpointer",
	Tag:           "varint,65012,opt,name=wktpointer",
	Filename:      "gsx.proto",
}

func init() {
	proto.RegisterExtension(E_GoprotoEnumPrefix)
	proto.RegisterExtension(E_GoprotoEnumStringer)
	proto.RegisterExtension(E_EnumStringer)
	proto.RegisterExtension(E_EnumCustomname)
	proto.RegisterExtension(E_Enumdecl)
	proto.RegisterExtension(E_EnumvalueCustomname)
	proto.RegisterExtension(E_GoprotoGettersAll)
	proto.RegisterExtension(E_GoprotoEnumPrefixAll)
	proto.RegisterExtension(E_GoprotoStringerAll)
	proto.RegisterExtension(E_VerboseEqualAll)
	proto.RegisterExtension(E_FaceAll)
	proto.RegisterExtension(E_GostringAll)
	proto.RegisterExtension(E_PopulateAll)
	proto.RegisterExtension(E_StringerAll)
	proto.RegisterExtension(E_OnlyoneAll)
	proto.RegisterExtension(E_EqualAll)
	proto.RegisterExtension(E_DescriptionAll)
	proto.RegisterExtension(E_TestgenAll)
	proto.RegisterExtension(E_BenchgenAll)
	proto.RegisterExtension(E_MarshalerAll)
	proto.RegisterExtension(E_UnmarshalerAll)
	proto.RegisterExtension(E_StableMarshalerAll)
	proto.RegisterExtension(E_SizerAll)
	proto.RegisterExtension(E_GoprotoEnumStringerAll)
	proto.RegisterExtension(E_EnumStringerAll)
	proto.RegisterExtension(E_UnsafeMarshalerAll)
	proto.RegisterExtension(E_UnsafeUnmarshalerAll)
	proto.RegisterExtension(E_GoprotoExtensionsMapAll)
	proto.RegisterExtension(E_GoprotoUnrecognizedAll)
	proto.RegisterExtension(E_GogoprotoImport)
	proto.RegisterExtension(E_ProtosizerAll)
	proto.RegisterExtension(E_CompareAll)
	proto.RegisterExtension(E_TypedeclAll)
	proto.RegisterExtension(E_EnumdeclAll)
	proto.RegisterExtension(E_GoprotoRegistration)
	proto.RegisterExtension(E_MessagenameAll)
	proto.RegisterExtension(E_GoprotoSizecacheAll)
	proto.RegisterExtension(E_GoprotoUnkeyedAll)
	proto.RegisterExtension(E_GoprotoGetters)
	proto.RegisterExtension(E_GoprotoStringer)
	proto.RegisterExtension(E_VerboseEqual)
	proto.RegisterExtension(E_Face)
	proto.RegisterExtension(E_Gostring)
	proto.RegisterExtension(E_Populate)
	proto.RegisterExtension(E_Stringer)
	proto.RegisterExtension(E_Onlyone)
	proto.RegisterExtension(E_Equal)
	proto.RegisterExtension(E_Description)
	proto.RegisterExtension(E_Testgen)
	proto.RegisterExtension(E_Benchgen)
	proto.RegisterExtension(E_Marshaler)
	proto.RegisterExtension(E_Unmarshaler)
	proto.RegisterExtension(E_StableMarshaler)
	proto.RegisterExtension(E_Sizer)
	proto.RegisterExtension(E_UnsafeMarshaler)
	proto.RegisterExtension(E_UnsafeUnmarshaler)
	proto.RegisterExtension(E_GoprotoExtensionsMap)
	proto.RegisterExtension(E_GoprotoUnrecognized)
	proto.RegisterExtension(E_Protosizer)
	proto.RegisterExtension(E_Compare)
	proto.RegisterExtension(E_Typedecl)
	proto.RegisterExtension(E_Messagename)
	proto.RegisterExtension(E_GoprotoSizecache)
	proto.RegisterExtension(E_GoprotoUnkeyed)
	proto.RegisterExtension(E_Nullable)
	proto.RegisterExtension(E_Embed)
	proto.RegisterExtension(E_Customtype)
	proto.RegisterExtension(E_Customname)
	proto.RegisterExtension(E_Jsontag)
	proto.RegisterExtension(E_Moretags)
	proto.RegisterExtension(E_Casttype)
	proto.RegisterExtension(E_Castkey)
	proto.RegisterExtension(E_Castvalue)
	proto.RegisterExtension(E_Stdtime)
	proto.RegisterExtension(E_Stdduration)
	proto.RegisterExtension(E_Wktpointer)
}

func init() { proto.RegisterFile("gsx.proto", fileDescriptor_987a9d6f024154f0) }

var fileDescriptor_987a9d6f024154f0 = []byte{
	// 1291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x98, 0x49, 0x6f, 0x1c, 0x45,
	0x14, 0x80, 0x85, 0xe2, 0xc8, 0x9e, 0xf2, 0x16, 0x8f, 0x8d, 0x09, 0x11, 0x88, 0x70, 0xe3, 0xe4,
	0x9c, 0x22, 0x94, 0xb2, 0x22, 0xcb, 0xb2, 0x1c, 0x2b, 0x08, 0x07, 0xe3, 0xc4, 0x01, 0xc4, 0x61,
	0xd4, 0x9e, 0x29, 0xb7, 0x1b, 0xf7, 0x46, 0x57, 0x75, 0xb0, 0x73, 0x43, 0x61, 0x11, 0x42, 0xec,
	0x48, 0x90, 0x90, 0x04, 0x02, 0x62, 0x5f, 0xc3, 0xbe, 0x5c, 0xb8, 0xb0, 0x5c, 0xf9, 0x0f, 0x5c,
	0x00, 0xb3, 0xfb, 0xe6, 0x4b, 0xf4, 0xba, 0xdf, 0xeb, 0xa9, 0xee, 0x19, 0xa9, 0x6a, 0x6e, 0x93,
	0x49, 0x7d, 0xdf, 0x54, 0xbf, 0x57, 0xf5, 0xde, 0x73, 0xb3, 0x9a, 0x2b, 0x37, 0xa7, 0xe2, 0x24,
	0x52, 0x51, 0x7d, 0x8f, 0x2b, 0x37, 0x0f, 0x1c, 0x74, 0xa3, 0xc8, 0xf5, 0xc5, 0xa1, 0xec, 0xab,
	0xd5, 0x74, 0xed, 0x50, 0x4b, 0xc8, 0x66, 0xe2, 0xc5, 0x2a, 0x4a, 0xf2, 0x65, 0xfc, 0x04, 0x1b,
	0x77, 0xa3, 0xec, 0x63, 0x43, 0x84, 0x69, 0xd0, 0x88, 0x13, 0xb1, 0xe6, 0x6d, 0xd6, 0x6f, 0x9a,
	0xca, 0xc9, 0x29, 0x22, 0xa7, 0xe6, 0xc3, 0x34, 0xb8, 0x2b, 0x56, 0x5e, 0x14, 0xca, 0xfd, 0x57,
	0x7f, 0xdd, 0x73, 0xf0, 0xba, 0xdb, 0x06, 0x96, 0xc7, 0x10, 0x85, 0xff, 0x5b, 0xca, 0x40, 0xbe,
	0xcc, 0xae, 0x2f, 0xf9, 0xa4, 0x4a, 0xbc, 0xd0, 0x15, 0x89, 0xc1, 0xf8, 0x03, 0x1a, 0xc7, 0x35,
	0xe3, 0x49, 0x44, 0xf9, 0x1c, 0x1b, 0xee, 0xc5, 0xf5, 0x23, 0xba, 0x86, 0x84, 0x2e, 0x59, 0x60,
	0xa3, 0x99, 0xa4, 0x99, 0x4a, 0x15, 0x05, 0xa1, 0x13, 0x08, 0x83, 0xe6, 0xa7, 0x4c, 0x53, 0x5b,
	0x1e, 0x01, 0x6c, 0xae, 0xa0, 0x38, 0x67, 0x03, 0xf0, 0x4d, 0x4b, 0x34, 0x7d, 0x83, 0xe1, 0x67,
	0xdc, 0x48, 0xb1, 0x9e, 0x9f, 0x66, 0x13, 0xf0, 0xf9, 0x8c, 0xe3, 0xa7, 0x42, 0xdf, 0xc9, 0xad,
	0x5d, 0x3d, 0xa7, 0x61, 0x19, 0xc9, 0x7e, 0x39, 0xd7, 0x97, 0x6d, 0x67, 0xbc, 0x10, 0x68, 0x7b,
	0xd2, 0xb2, 0xe8, 0x0a, 0xa5, 0x44, 0x22, 0x1b, 0x8e, 0xdf, 0x6d, 0x7b, 0xc7, 0x3c, 0xbf, 0x30,
	0x9e, 0xdf, 0x2e, 0x67, 0x71, 0x21, 0x27, 0x67, 0x7d, 0x9f, 0xaf, 0xb0, 0x1b, 0xba, 0x9c, 0x0a,
	0x0b, 0xe7, 0x05, 0x74, 0x4e, 0x74, 0x9c, 0x0c, 0xd0, 0x2e, 0x31, 0xfa, 0xbe, 0xc8, 0xa5, 0x85,
	0xf3, 0x15, 0x74, 0xd6, 0x91, 0xa5, 0x94, 0x82, 0xf1, 0x0e, 0x36, 0x76, 0x46, 0x24, 0xab, 0x91,
	0x14, 0x0d, 0xf1, 0x60, 0xea, 0xf8, 0x16, 0xba, 0x8b, 0xa8, 0x1b, 0x45, 0x70, 0x1e, 0x38, 0x70,
	0x1d, 0x61, 0x03, 0x6b, 0x4e, 0x53, 0x58, 0x28, 0x2e, 0xa1, 0xa2, 0x1f, 0xd6, 0x03, 0x3a, 0xcb,
	0x86, 0xdc, 0x28, 0x7f, 0x24, 0x0b, 0xfc, 0x32, 0xe2, 0x83, 0xc4, 0xa0, 0x22, 0x8e, 0xe2, 0xd4,
	0x77, 0x94, 0xcd, 0x0e, 0x5e, 0x25, 0x05, 0x31, 0xa8, 0xe8, 0x21, 0xac, 0xaf, 0x91, 0x42, 0x6a,
	0xf1, 0x9c, 0x61, 0x83, 0x51, 0xe8, 0x6f, 0x45, 0xa1, 0xcd, 0x26, 0xae, 0xa0, 0x81, 0x21, 0x02,
	0x82, 0x69, 0x56, 0xb3, 0x4d, 0xc4, 0x9b, 0xdb, 0x74, 0x3d, 0x28, 0x03, 0x0b, 0x6c, 0x94, 0x0a,
	0x94, 0x17, 0x85, 0x16, 0x8a, 0xb7, 0x50, 0x31, 0xa2, 0x61, 0xf8, 0x18, 0x4a, 0x48, 0xe5, 0x0a,
	0x1b, 0xc9, 0xdb, 0xf4, 0x18, 0x88, 0x60, 0x28, 0x57, 0x45, 0xd8, 0x5c, 0xb7, 0x33, 0xbc, 0x43,
	0xa1, 0x24, 0x06, 0x14, 0x73, 0x6c, 0x38, 0x70, 0x12, 0xb9, 0xee, 0xf8, 0x56, 0xe9, 0x78, 0x17,
	0x1d, 0x43, 0x05, 0x84, 0x11, 0x49, 0xc3, 0x5e, 0x34, 0xef, 0x51, 0x44, 0x34, 0x0c, 0xaf, 0x9e,
	0x54, 0xce, 0xaa, 0x2f, 0x1a, 0xbd, 0xd8, 0xde, 0xa7, 0xab, 0x97, 0xb3, 0x8b, 0xba, 0x71, 0x9a,
	0xd5, 0xa4, 0x77, 0xd6, 0x4a, 0xf3, 0x01, 0x65, 0x3a, 0x03, 0x00, 0xbe, 0x8f, 0xdd, 0xd8, 0xb5,
	0x4d, 0x58, 0xc8, 0x3e, 0x44, 0xd9, 0x64, 0x97, 0x56, 0x81, 0x25, 0xa1, 0x57, 0xe5, 0x47, 0x54,
	0x12, 0x44, 0xc5, 0xb5, 0xc4, 0x26, 0xd2, 0x50, 0x3a, 0x6b, 0xbd, 0x45, 0xed, 0x63, 0x8a, 0x5a,
	0xce, 0x96, 0xa2, 0x76, 0x8a, 0x4d, 0xa2, 0xb1, 0xb7, 0xbc, 0x7e, 0x42, 0x85, 0x35, 0xa7, 0x57,
	0xca, 0xd9, 0xbd, 0x9f, 0x1d, 0x28, 0xc2, 0xb9, 0xa9, 0x44, 0x28, 0x81, 0x69, 0x04, 0x4e, 0x6c,
	0x61, 0xbe, 0x8a, 0x66, 0xaa, 0xf8, 0xf3, 0x85, 0x60, 0xd1, 0x89, 0x41, 0x7e, 0x2f, 0xdb, 0x4f,
	0xf2, 0x34, 0x4c, 0x44, 0x33, 0x72, 0x43, 0xef, 0xac, 0x68, 0x59, 0xa8, 0x3f, 0xad, 0xa4, 0x6a,
	0x45, 0xc3, 0xc1, 0x7c, 0x9c, 0xed, 0x73, 0x23, 0x72, 0x7b, 0x41, 0x1c, 0x25, 0xca, 0x60, 0xfc,
	0x8c, 0x32, 0x55, 0x70, 0xc7, 0x33, 0x8c, 0xcf, 0xb3, 0x91, 0xec, 0x9f, 0xb6, 0x47, 0xf2, 0x73,
	0x14, 0x0d, 0xb7, 0x29, 0x2c, 0x1c, 0xcd, 0x28, 0x88, 0x9d, 0xc4, 0xa6, 0xfe, 0x7d, 0x41, 0x85,
	0x03, 0x11, 0x2c, 0x1c, 0x6a, 0x2b, 0x16, 0xd0, 0xed, 0x2d, 0x0c, 0x5f, 0x52, 0xe1, 0x20, 0x06,
	0x15, 0x34, 0x30, 0x58, 0x28, 0xbe, 0x22, 0x05, 0x31, 0xa0, 0xb8, 0xbb, 0xdd, 0x68, 0x13, 0xe1,
	0x7a, 0x52, 0x25, 0x0e, 0xac, 0x36, 0xa8, 0xbe, 0xde, 0x2e, 0x0f, 0x61, 0xcb, 0x1a, 0x0a, 0x95,
	0x28, 0x10, 0x52, 0x3a, 0xae, 0x80, 0x89, 0xc3, 0x62, 0x63, 0xdf, 0x50, 0x25, 0xd2, 0x30, 0xd8,
	0x9b, 0x36, 0x21, 0x42, 0xd8, 0x9b, 0x4e, 0x73, 0xdd, 0x46, 0xf7, 0x6d, 0x65, 0x73, 0x27, 0x89,
	0x05, 0xa7, 0x36, 0xff, 0xa4, 0xe1, 0x86, 0xd8, 0xb2, 0x3a, 0x9d, 0xdf, 0x55, 0xe6, 0x9f, 0x95,
	0x9c, 0xcc, 0x6b, 0xc8, 0x68, 0x65, 0x9e, 0xaa, 0xdf, 0xd2, 0xe1, 0x5a, 0xcc, 0x9f, 0x8b, 0x74,
	0x0f, 0xef, 0xe0, 0xf3, 0x96, 0xc7, 0x29, 0x7e, 0x27, 0x1c, 0xf2, 0xf2, 0xd0, 0x63, 0x96, 0x9d,
	0xdb, 0x29, 0xce, 0x79, 0x69, 0xe6, 0xe1, 0xc7, 0xd8, 0x70, 0x69, 0xe0, 0x31, 0xab, 0x1e, 0x41,
	0xd5, 0x90, 0x3e, 0xef, 0xf0, 0xc3, 0xac, 0x0f, 0x86, 0x17, 0x33, 0xfe, 0x28, 0xe2, 0xd9, 0x72,
	0x7e, 0x94, 0x0d, 0xd0, 0xd0, 0x62, 0x46, 0x1f, 0x43, 0xb4, 0x40, 0x00, 0xa7, 0x81, 0xc5, 0x8c,
	0x3f, 0x4e, 0x38, 0x21, 0x80, 0xdb, 0x87, 0xf0, 0xfb, 0x27, 0xfb, 0xb0, 0xe9, 0x50, 0xec, 0xa6,
	0x59, 0x3f, 0x4e, 0x2a, 0x66, 0xfa, 0x09, 0xfc, 0x71, 0x22, 0xf8, 0xed, 0x6c, 0xaf, 0x65, 0xc0,
	0x9f, 0x42, 0x34, 0x5f, 0xcf, 0xe7, 0xd8, 0xa0, 0x36, 0x9d, 0x98, 0xf1, 0xa7, 0x11, 0xd7, 0x29,
	0xd8, 0x3a, 0x4e, 0x27, 0x66, 0xc1, 0x33, 0xb4, 0x75, 0x24, 0x20, 0x6c, 0x34, 0x98, 0x98, 0xe9,
	0x67, 0x29, 0xea, 0x84, 0xf0, 0x19, 0x56, 0x2b, 0x9a, 0x8d, 0x99, 0x7f, 0x0e, 0xf9, 0x36, 0x03,
	0x11, 0xd0, 0x9a, 0x9d, 0x59, 0xf1, 0x3c, 0x45, 0x40, 0xa3, 0xe0, 0x1a, 0x55, 0x07, 0x18, 0xb3,
	0xe9, 0x05, 0xba, 0x46, 0x95, 0xf9, 0x05, 0xb2, 0x99, 0xd5, 0x7c, 0xb3, 0xe2, 0x45, 0xca, 0x66,
	0xb6, 0x1e, 0xb6, 0x51, 0x9d, 0x08, 0xcc, 0x8e, 0x97, 0x68, 0x1b, 0x95, 0x81, 0x80, 0x2f, 0xb1,
	0x7a, 0xe7, 0x34, 0x60, 0xf6, 0xbd, 0x8c, 0xbe, 0xb1, 0x8e, 0x61, 0x80, 0xdf, 0xc3, 0x26, 0xbb,
	0x4f, 0x02, 0x66, 0xeb, 0xf9, 0x9d, 0xca, 0xdf, 0x6e, 0xfa, 0x20, 0xc0, 0x4f, 0xb5, 0x5b, 0x8a,
	0x3e, 0x05, 0x98, 0xb5, 0x17, 0x76, 0xca, 0x85, 0x5b, 0x1f, 0x02, 0xf8, 0x2c, 0x63, 0xed, 0x06,
	0x6c, 0x76, 0x5d, 0x44, 0x97, 0x06, 0xc1, 0xd5, 0xc0, 0xfe, 0x6b, 0xe6, 0x2f, 0xd1, 0xd5, 0x40,
	0x02, 0xae, 0x06, 0xb5, 0x5e, 0x33, 0x7d, 0x99, 0xae, 0x06, 0x21, 0x70, 0xb2, 0xb5, 0xee, 0x66,
	0x36, 0x5c, 0xa1, 0x93, 0xad, 0x51, 0xfc, 0x04, 0x1b, 0xeb, 0x68, 0x88, 0x66, 0xd5, 0xeb, 0xa8,
	0xda, 0x57, 0xed, 0x87, 0x7a, 0xf3, 0xc2, 0x66, 0x68, 0xb6, 0xbd, 0x51, 0x69, 0x5e, 0xd8, 0x0b,
	0xf9, 0x34, 0x1b, 0x08, 0x53, 0xdf, 0x87, 0xcb, 0x53, 0xbf, 0xb9, 0x4b, 0x37, 0x15, 0x7e, 0x8b,
	0x14, 0xbf, 0xed, 0x62, 0x74, 0x08, 0xe0, 0x87, 0xd9, 0x5e, 0x11, 0xac, 0x8a, 0x96, 0x89, 0xfc,
	0x7d, 0x97, 0x0a, 0x26, 0xac, 0xe6, 0x33, 0x8c, 0xe5, 0xaf, 0x46, 0x20, 0xcc, 0x26, 0xf6, 0x8f,
	0xdd, 0xfc, 0x2d, 0x8d, 0x86, 0xb4, 0x05, 0x59, 0x52, 0x0c, 0x82, 0xed, 0xb2, 0x20, 0xcb, 0xc8,
	0x11, 0xd6, 0xff, 0x80, 0x8c, 0x42, 0xe5, 0xb8, 0x26, 0xfa, 0x4f, 0xa4, 0x69, 0x3d, 0x04, 0x2c,
	0x88, 0x12, 0xa1, 0x1c, 0x57, 0x9a, 0xd8, 0xbf, 0x90, 0x2d, 0x00, 0x80, 0x9b, 0x8e, 0x54, 0x36,
	0xcf, 0xfd, 0x37, 0xc1, 0x04, 0xc0, 0xa6, 0xe1, 0xf3, 0x86, 0xd8, 0x32, 0xb1, 0xff, 0xd0, 0xa6,
	0x71, 0x3d, 0x3f, 0xca, 0x6a, 0xf0, 0x31, 0x7b, 0xab, 0x64, 0x82, 0xff, 0x45, 0xb8, 0x4d, 0xc0,
	0x2f, 0x4b, 0xd5, 0x52, 0x9e, 0x39, 0xd8, 0xff, 0x61, 0xa6, 0x69, 0x3d, 0x9f, 0x65, 0x83, 0x52,
	0xb5, 0x5a, 0x29, 0xce, 0xa7, 0x06, 0xfc, 0xff, 0xdd, 0xe2, 0x95, 0x45, 0xc1, 0x40, 0xb6, 0x1f,
	0xda, 0x50, 0x71, 0xe4, 0x85, 0x4a, 0x24, 0x26, 0xc3, 0x0e, 0x1a, 0x34, 0xe4, 0x5a, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x62, 0x9d, 0xb4, 0x12, 0x35, 0x15, 0x00, 0x00,
}
